#!/usr/bin/env bash
if [ -z $1 ]
then
    echo "Please provide a name for your \"Cake making ingredient\""
    exit 1
fi
echo "Here is a nice non-yeasty script for you. Enjoy."
cp yeast $1
cat $1 | sed "s/yeast/$1/g" > $1.tmp && mv $1.tmp $1
chmod a+x $1
